Detect Language of Input
googleinterns/step36-2020 pull request #116
Opened 2020-08-04 22:48 UTC by nssafir

Detect the language of the input message (for text). Convert the language to a corresponding country, and country as a parameter of the news servlet if there is not already a country provided from the location.

2020-08-05 00:01 UTC, juanuribe28 requested changes

2020-08-05 00:01 UTC, juanuribe28 commented on pom.xml
> +          <deploy.projectId>nsafir-step</deploy.projectId>
Change it back

2020-08-05 00:01 UTC, juanuribe28 commented on src/main/webapp/scripts/toggle.js
> +  let keywordsJson = await loadKeywords(KEYWORDS_OBJ_URL);
[Optional] Use const to show that you're not changing it.

2020-08-05 00:01 UTC, juanuribe28 commented on src/main/webapp/scripts/toggle.js
> +    let keywordsJson = JSON.stringify(keywords);
Why did you change it from const to let?

2020-08-05 00:01 UTC, juanuribe28 commented on src/main/webapp/scripts/toggle.js
> +  let keywordsJson = await loadKeywords(KEYWORDS_OBJ_URL);
[Otional] By convention I have used suffix Json if it is a json string and Obj if it is an object. So in this case I would use keywordsObj instead of keywordsJson

2020-08-05 18:17 UTC, juanuribe28 approved these changes

2020-08-05 20:16 UTC, daperlmut requested changes

2020-08-05 20:16 UTC, daperlmut commented on src/main/java/com/google/sps/data/Keywords.java
> +      // Map the key to its respective collection of keywords
[Nit] Add a '.'

2020-08-06 19:47 UTC, daperlmut approved these changes

2020-08-06 20:55 UTC, merged