Implement Location Servlet
googleinterns/step36-2020 pull request #17
Opened 2020-07-01 22:17 UTC by nssafir

Implement a location servlet that uses Google's Geocoder API to get important features (ex. street name, city, ZIP code) from a user's location coordinates. This will later fed into the Google Civic API to get users in touch with their local politicians. Later, I will need to implement a doPost() method with Google's geolocation API to get the user's coordinates if they consent.

2020-07-01 22:40 UTC, juanuribe28 commented on src/main/java/com/google/sps/servlets/LocationServlet.java
> +        for (int i = 0; i < addressArray.size(); i++){
[Optional] A comment here to explain the logic would be useful.

2020-07-01 22:40 UTC, juanuribe28 commented on src/main/java/com/google/sps/servlets/LocationServlet.java
> +          if (geoType.equals("locality")) {
I know switch statements are not ideal, but this seems like a a good place to use one.

2020-07-01 22:40 UTC, juanuribe28 commented on src/test/java/com/google/sps/LocationTest.java
> +package com.google.sps;
I would leave this file out of this PR, as it doesn't contain any tests.

2020-07-03 17:45 UTC, juanuribe28 requested changes

2020-07-03 17:45 UTC, juanuribe28 commented on src/main/java/com/google/sps/servlets/LocationServlet.java
> +          switch (geoType) {
[Nit] It requires a default label, even if it is empty.

2020-07-06 16:30 UTC, juanuribe28 approved these changes

2020-07-06 21:26 UTC, seangilpin approved these changes

2020-07-07 13:34 UTC, merged