Add a general front-end to the main page.
googleinterns/step36-2020 pull request #2
Opened 2020-06-24 06:08 UTC by juanuribe28

The front-end uses mustache to render the specific menu sections. The content of the templates is just there to show this behavior, they don't contain any other meaningful content.

2020-06-24 06:15 UTC, juanuribe28 commented
@googlebot I signed it!

2020-06-24 16:38 UTC, dranilew requested changes
Small nit, everything else looks good to me.

2020-06-24 16:38 UTC, P3BBL35 commented on src/main/webapp/scripts/toggle.js
> +  for (let i = 0; i < sectionsNames.length; i++){
[Nit] Add space before the opening bracket

2020-06-24 17:16 UTC, dranilew approved these changes

2020-06-25 07:36 UTC, daperlmut requested changes

2020-06-25 07:36 UTC, daperlmut commented on src/main/webapp/scripts/toggle.js
> +const htmlSectionsPromises = loadHtmlSections(templatesUrls, objectsUrls, sectionsNames);
For module level constants use CONST_CASE instead of lowerCamelCase

2020-06-25 19:23 UTC, daperlmut approved these changes

2020-06-25 19:24 UTC, merged