Implement Google civic API backend
googleinterns/step36-2020 pull request #22
Opened 2020-07-07 19:37 UTC by juanuribe28

Add civic servlet to query information about the representatives that are in charge of the user's division.

2020-07-07 20:35 UTC, nssafir commented on src/main/java/com/google/sps/servlets/CivicServlet.java
> +}
[Nit] add newline

2020-07-07 20:48 UTC, dranilew requested changes

2020-07-07 20:48 UTC, P3BBL35 commented on src/main/java/com/google/sps/servlets/CivicServlet.java
> +      // Location URL doesn't work on devserver, so isntead use hardcoded string.
[Nit] "Instead" spelled incorrectly.

2020-07-07 20:48 UTC, P3BBL35 commented on src/main/java/com/google/sps/servlets/CivicServlet.java
> +      System.out.println(fnfe);
[Optional] You can alternatively use `fnfe.printStackTrace();` instead.

2020-07-08 02:03 UTC, dranilew requested changes

2020-07-08 02:03 UTC, P3BBL35 commented on src/main/java/com/google/sps/servlets/CivicServlet.java
> +      System.out.println(fnfe.printStackTrace());
[Nit] .printStackTrace() already prints the stack trace to System.out, so `System.out.println()` is unnecessary.

2020-07-08 18:43 UTC, dranilew approved these changes

2020-07-09 00:31 UTC, daperlmut requested changes

2020-07-09 00:31 UTC, daperlmut commented on src/main/java/com/google/sps/servlets/CivicServlet.java
> +      // Location URL doesn't work on devserver, so instead use hardcoded string.
[Nit] I think this comment makes more sense if you put it in the catch block below.

2020-07-09 00:53 UTC, daperlmut approved these changes

2020-07-09 05:13 UTC, merged