Make Maven Command Line Arguments for API Keys
googleinterns/step36-2020 pull request #55
Opened 2020-07-15 20:59 UTC by nssafir

To not have to manually enter each API key each time to test, the API keys are passed as command line arguments. Check the readme for more instructions about how to use it.

2020-07-15 22:01 UTC, juanuribe28 requested changes
This is really interesting.

2020-07-15 22:01 UTC, juanuribe28 commented on src/main/java/com/google/sps/data/GetAPIKeyUtil.java
> +}
[Nit] Add newline.

2020-07-15 22:01 UTC, juanuribe28 commented on src/main/java/com/google/sps/data/GetAPIKeyUtil.java
> +
[Nit] Remove new line.

2020-07-15 22:01 UTC, juanuribe28 commented on src/main/java/com/google/sps/data/GetAPIKeyUtil.java
> +    System.out.println("in getAPIKey");
Was this print statement for testing?

2020-07-15 22:01 UTC, juanuribe28 commented on README.md
> +To run, use the following command: 	`[mvn command] -DbooksKey=[Google Books API Key] -DprojectsKey=[Global Giving API Key] -DcivicsKey=[Google Civics API Key] -DlocationKey=[Google Geocoder API Key]`
We could probably use the same API key for all the google apis.

2020-07-15 22:01 UTC, juanuribe28 commented on src/main/resources/project.properties
> +locationKey = ${locationKey}
[Nit] Add new line.

2020-07-16 16:07 UTC, nssafir commented on src/main/java/com/google/sps/data/GetAPIKeyUtil.java
> +    System.out.println("in getAPIKey");
Yes, forgot to take it out

2020-07-16 16:08 UTC, nssafir commented on README.md
> +To run, use the following command: 	`[mvn command] -DbooksKey=[Google Books API Key] -DprojectsKey=[Global Giving API Key] -DcivicsKey=[Google Civics API Key] -DlocationKey=[Google Geocoder API Key]`
I'm going to look into this

2020-07-16 22:00 UTC, juanuribe28 approved these changes

2020-07-16 23:47 UTC, seangilpin approved these changes
Very nice!

2020-07-17 19:53 UTC, merged