Add instructions
googleinterns/step36-2020 pull request #61
Opened 2020-07-16 19:28 UTC by nssafir

Add instructions to the left side of the homepage.

2020-07-16 21:13 UTC, juanuribe28 requested changes

2020-07-16 21:13 UTC, juanuribe28 commented on src/main/webapp/styles/index.css
> +  padding: 20px;
[Nit] Replace px with some relative unit (vw, vh, vmin, vmax) to adapt to different screen sizes.

2020-07-16 21:13 UTC, juanuribe28 commented on src/main/webapp/styles/index.css
> +  padding: 20px;
Same with px

2020-07-17 15:43 UTC, juanuribe28 approved these changes

2020-07-17 15:43 UTC, juanuribe28 commented on src/main/webapp/styles/index.css
> +  margin: 0px;
[Optional] When setting a property to 0 you don't need to include units.

2020-07-17 15:43 UTC, juanuribe28 commented on src/main/webapp/styles/index.css
> +  margin: 0px;
[Optional] same as above

2020-07-17 21:26 UTC, daperlmut approved these changes

2020-07-17 21:26 UTC, daperlmut commented on src/main/webapp/index.html
> +        on the right side of the screen.
[Optional] I'd create a second paragraph starting with "If you'd like to contact..."

2020-07-21 14:00 UTC, merged