Attempt text detection first before resorting to label detection
googleinterns/step36-2020 pull request #71
Opened 2020-07-23 16:17 UTC by P3BBL35

There seems to be a small problem with the number of keywords that pop out from the text_detection as although it reads the whole text on the image (sometimes incorrectly), I think the threshold makes it so that a lot of the keywords don't end up showing up in the final returned list. So, I may need to re-adjust some of the thresholds as they were mainly for label detection and the likes, and text_detection seems to have slightly different results. Namely, a lot of the important keywords ended up having a salience of under 0.1 (like around 0.9), which voided them from the list.

2020-07-23 23:03 UTC, nssafir commented on src/main/java/com/google/sps/servlets/ImageServlet.java
[Nit] delete newline

2020-07-23 23:03 UTC, nssafir commented on src/main/java/com/google/sps/servlets/ImageServlet.java
> +
[Nit] delete newline

2020-07-24 18:50 UTC, juanuribe28 commented on src/main/java/com/google/sps/servlets/ImageServlet.java
> +      System.err.println("Error getting image labels or text: " + imageResponse.getError().getMessage());
[Optional] Make custom error message.
`String.format("Error getting image %s: %s", (useTextDetection) ? "text" : "labels",  imageResponse.getError().getMessage()`

2020-07-25 00:48 UTC, juanuribe28 approved these changes

2020-07-25 03:57 UTC, daperlmut requested changes

2020-07-25 03:57 UTC, daperlmut commented on src/main/java/com/google/sps/servlets/ImageServlet.java
> +      System.err.println(String.format("Error getting image %s: %s ", (useTextDetection) ? "text" : "labels", imageResponse.getError().getMessage()));
[Nit] Please please this into shorter lines.  

I would use a local variable for the ternary statement result to make this a bit more readable as well.

2020-07-26 03:28 UTC, daperlmut approved these changes

2020-07-27 15:06 UTC, merged