Added link to website in README
googleinterns/step36-2020 pull request #75
Opened 2020-07-24 18:17 UTC by nssafir

Added link to our website in ReadMe. Also may want to make deployment log in the future.

2020-07-24 18:42 UTC, juanuribe28 commented
#76

2020-07-24 18:44 UTC, juanuribe28 requested changes

2020-07-24 18:44 UTC, juanuribe28 commented on README.md
> +Link to the Website: https://step2020-team36-capstone.uc.r.appspot.com/
[Nit] Remove .uc.r (https://step2020-team36-capstone.appspot.com/)

2020-07-25 00:37 UTC, juanuribe28 approved these changes

2020-07-25 01:16 UTC, daperlmut approved these changes

2020-07-25 02:41 UTC, merged